FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Sweeper/Sweeper.csproj", "Sweeper/"]
COPY ["Components/Components.csproj", "Components/"]
RUN dotnet restore "Sweeper/Sweeper.csproj"

COPY . .
RUN dotnet publish -c Release -o /app Sweeper/Sweeper.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS publish
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["/bin/bash", "-c", "sleep 40 && dotnet Sweeper.dll"]