FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CreateDb/CreateDb.csproj", "CreateDb/"]
COPY ["Components/Components.csproj", "Components/"]
RUN dotnet restore "CreateDb/CreateDb.csproj"

COPY . .
RUN dotnet publish -c Release -o /app CreateDb/CreateDb.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS publish
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "CreateDb.dll"]